CREATE OR REPLACE PROCEDURE product_api_dbo.aip_store_card_products (p_product_id_i VARCHAR(300),
																	p_product_name_i VARCHAR(100),
																	p_brand_i		VARCHAR(50),
																	p_product_category_i VARCHAR(100),
																	p_game_or_sport_i	VARCHAR(10),
																	p_set_name_i			VARCHAR(50),
																	p_release_date_i		DATE,
																	p_product_type_i		VARCHAR(50),
																	p_pack_count_i		INTEGER,
																	p_card_count_per_pack_i INTEGER,
																	p_total_card_count_i	INTEGER,
																	p_promo_included_i	BOOLEAN,
																	p_promo_details_i		VARCHAR(300),
																	p_msrp_i				DECIMAL(10, 2),
																	p_cost_price_i		DECIMAL(10, 2),
																	p_sale_price_i		DECIMAL(10, 2),
																	p_sku_i				VARCHAR(100),
																	p_barcode_i			VARCHAR(300),
																	p_inventory_count_i	INTEGER,
																	p_image_url_i			VARCHAR(300),
																	p_description_i		VARCHAR(300),
																	p_sealed_i			BOOLEAN,
																	p_is_active_i		BOOLEAN)
AS $$
BEGIN
  INSERT INTO product_dbo.card_product (product_id,
										product_name,
										brand,
										product_category,
										game_or_sport,
										set_name,
										release_date,
										product_type,
										pack_count,
										card_count_per_pack,
										total_card_count,
										promo_included,
										promo_details,
										msrp,
										cost_price,
										sale_price,
										sku,
										barcode,
										inventory_count,
										image_url,
										description,
										sealed,
										is_active,
										create_id,
										create_ts)
						VALUES (p_product_id,
										p_product_name_i,
										p_brand_i,
										p_product_category_i,
										p_game_or_sport_i,
										p_set_name_i,
										p_release_date_i,
										p_product_type_i,
										p_pack_count_i,
										p_card_count_per_pack_i,
										p_total_card_count_i,
										p_promo_included_i,
										p_promo_details_i,
										p_msrp_i,
										p_cost_price_i,
										p_sale_price_i,
										p_sku_i,
										p_barcode_i,
										p_inventory_count_i,
										p_image_url_i,
										p_description_i,
										p_sealed_i,
										p_is_active_i,
										CURRENT_USER,
										CURRENT_TIMESTAMP);

EXCEPTION
  WHEN OTHERS THEN
    RAISE EXCEPTION 'Exception encountered for procedure product_api_dbo.aip_store_card_product (%)', SQLERRM;
END;
$$ LANGUAGE plpgsql;