CREATE TABLE RECORDS_DBO.MESSAGE_TRACKER (
	ID						VARCHAR(300) PRIMARY KEY,
	TELNYX_MESSAGE_ID 		VARCHAR(300), -- telnyx's message UUID
	MESSAGING_PROFILE_ID 	VARCHAR(300), -- your telnyx messaging profile
	FROM_NUMBER 			VARCHAR(20) NOT NULL, --E.164 FORMAT
	TO_NUMBER 				VARCHAR(20) NOT NULL,
	DIRECTION				VARCHAR(10) NOT NULL, -- 'inbound' or 'outbound'
	BODY					TEXT,
	MEDIA_URLS				TEXT[],
	STATUS					VARCHAR(50),  --queued, sent, delivered, failed
	ERROR_CODE				VARCHAR(50),
	ERROR_MESSAGE			TEXT,
	WEBHOOK_RECEIVED_TS		TIMESTAMP, --when the flask app received the webhook
	CARRIER					VARCHAR(100),
	SENT_TS					TIMESTAMP, --when telnyx sent/received it
	DELIVERED_TS			TIMESTAMP,
	CREATE_TS				TIMESTAMP,
	UPDATE_TS				TIMESTAMP
);
GRANT INSERT, UPDATE, DELETE, SELECT ON RECORDS_DBO.SHIPMENTS TO APPUSER;