CREATE TABLE IF NOT EXISTS RECORDS_DBO.SHIPMENTS (
    SHIPMENT_ID     VARCHAR(300) NOT NULL,
    TRACKING_ID     VARCHAR(300) NOT NULL,
    WEIGHT          DECIMAL(6, 2),
    WEIGHT_UNIT     VARCHAR(10),
    EST_DELIVERY_DATE   TIMESTAMP,
    DELIVERY_START_TS   TIMESTAMP,
    DELIVERY_END_TS      TIMESTAMP,
    CREATE_ID           VARCHAR(30) NOT NULL,
    CREATE_TS           TIMESTAMP NOT NULL,
    UPDATE_ID           VARCHAR(30),
    UPDATE_TS           TIMESTAMP
);
GRANT INSERT, UPDATE, DELETE, SELECT ON RECORDS_DBO.SHIPMENTS TO APPUSER;