CREATE TABLE RECORDS_DBO.USER_MESSAGING_STATUS (
	PHONE_NUMBER 	VARCHAR(20) PRIMARY KEY,
	STATUS_CD		VARCHAR(10) NOT NULL, --ACTIVE, INACTIVE
	CREATE_ID		VARCHAR(30) NOT NULL,
	CREATE_TS		TIMESTAMP NOT NULL,
	UPDATE_ID		VARCHAR(30),
	UPDATE_TS		TIMESTAMP
);
GRANT INSERT, UPDATE, DELETE, SELECT ON RECORDS_DBO.USER_MESSAGING_STATUS TO APPUSER;