CREATE TABLE IF NOT EXISTS RECORDS_DBO.SHIPMENT_ACTIVITIES (
    SHIPMENT_ACTIVITY_ID    VARCHAR(300) NOT NULL,
    SHIPMENT_ID             VARCHAR(300) NOT NULL,
    STATUS_TYPE_CD          VARCHAR(1) NOT NULL,
    EVENT_TS                TIMESTAMP,
    EVENT_CITY              VARCHAR(100),
    STATE_CD                VARCHAR(2),
    POSTAL_CD               VARCHAR(20),
    COUNTRY                 VARCHAR(10),
    CREATE_ID               VARCHAR(30) NOT NULL,
    CREATE_TS               TIMESTAMP NOT NULL,
    UPDATE_ID               VARCHAR(30),
    UPDATE_TS               TIMESTAMP
);
GRANT INSERT, UPDATE, DELETE, SELECT ON RECORDS_DBO.SHIPMENT_ACTIVITIES TO APPUSER;