CREATE TABLE IF NOT EXISTS RECORDS_DBO.TRANSACTIONS (
    TRANSACTION_ID VARCHAR(300) NOT NULL,
    SHIPMENT_ID     VARCHAR(300) NOT NULL,
    TRANSACTION_TS  TIMESTAMP NOT NULL,
    CARD_ID         VARCHAR(300),
    PRODUCT_ID      VARCHAR(300),
    TRANSACTION_AMT DECIMAL(10, 2),
    ACCOUNT_ID      VARCHAR(300),
    CURRENCY_CD     VARCHAR(4),
    PAYMENT_METHOD_CD   VARCHAR(4),
    CREATE_ID       VARCHAR(30) NOT NULL,
    CREATE_TS       TIMESTAMP NOT NULL,
    UPDATE_ID       VARCHAR(30),
    UPDATE_TS       TIMESTAMP
);
GRANT INSERT, UPDATE, DELETE, SELECT ON RECORDS_DBO.TRANSACTIONS TO APPUSER;