CREATE OR REPLACE PROCEDURE RECORDS_API_DBO.AIP_USER_MESSAGING_STATUS_INSERT (
	P_PHONE_NUMBER_I		IN VARCHAR(20),
	P_STATUS_CD_I			IN VARCHAR(10),
	P_CREATE_ID_I			IN VARCHAR(30)
)
AS $$
BEGIN
	IF P_PHONE_NUMBER_I IS NULL OR P_STATUS_CD_I IS NULL OR P_CREATE_ID_I IS NULL THEN
		RAISE EXCEPTION 'Input parameters cannot be null';
	END IF;

	IF NOT EXISTS (SELECT 1 FROM RECORDS_DBO.USER_MESSAGING_STATUS WHERE PHONE_NUMBER = P_PHONE_NUMBER_I) THEN
		INSERT INTO RECORDS_DBO.USER_MESSAGING_STATUS (
			PHONE_NUMBER,
			STATUS_CD,
			CREATE_ID,
			CREATE_TS
		) VALUES (
			P_PHONE_NUMBER_I,
			P_STATUS_CD_I,
			P_CREATE_ID_I,
			CURRENT_TIMESTAMP
		);
	ELSE
		UPDATE RECORDS_DBO.USER_MESSAGING_STATUS
		SET STATUS_CD = P_STATUS_CD_I,
			UPDATE_ID = P_CREATE_ID_I,
			UPDATE_TS = CURRENT_TIMESTAMP
		WHERE PHONE_NUMBER = P_PHONE_NUMBER_I;
	END IF;


	EXCEPTION WHEN OTHERS THEN
		RAISE EXCEPTION 'Error in AIP_USER_MESSAGING_STATUS_INSERT: %', SQLERRM;

END;
$$ LANGUAGE plpgsql;