CREATE OR REPLACE FUNCTION RECORDS_API_DBO.FETCH_USER_MESSAGING_BY_STATUS(P_STATUS_CD_I IN VARCHAR(10))
RETURNS TABLE ( P_PHONE_NUMBER_O VARCHAR(20),
				P_STATUS_O		 VARCHAR(10) )
AS $$
BEGIN
	RETURN QUERY
	SELECT 
		PHONE_NUMBER,
		STATUS_CD
	FROM USER_MESSAGING_STATUS
	WHERE STATUS_CD = COALESCE(P_STATUS_CD_I, STATUS_CD);
	
	EXCEPTION
		WHEN OTHERS THEN
			RAISE EXCEPTION 'Error in function fetch_user_by_status (%)', SQLERRM;
END;
$$ LANGUAGE plpgsql;